src/Entity/AdminBan.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminBanRepository")
 */
class AdminBan
{
    const BanTypeLogin = 1;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bannings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sourceUser;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Post")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $post;

    /**
     * @ORM\Column(type="string")
     */
    private $reason;

    /**
     * @ORM\Column(type="datetime")
     */
    private $banStart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $banEnd;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $lifted = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $liftUser;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSourceUser(): ?User
    {
        return $this->sourceUser;
    }

    public function setSourceUser(User $sourceUser): self
    {
        $this->sourceUser = $sourceUser;

        return $this;
    }

    public function getBanStart(): ?\DateTimeInterface
    {
        return $this->banStart;
    }

    public function setBanStart(\DateTimeInterface $banStart): self
    {
        $this->banStart = $banStart;

        return $this;
    }

    public function getBanEnd(): ?\DateTimeInterface
    {
        return $this->banEnd;
    }

    public function setBanEnd(\DateTimeInterface $banEnd): self
    {
        $this->banEnd = $banEnd;

        return $this;
    }

    public function getActive(): bool
    {
        if ($this->getBanEnd() > new DateTime("now") && !( $this->getLifted() )) return true;
        return false;
    }

    public function setReason(string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setPost(Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function getLifted(): ?bool
    {
        return $this->lifted;
    }

    public function setLifted(?bool $lifted): self
    {
        $this->lifted = $lifted;

        return $this;
    }

    public function getLiftUser(): ?User
    {
        return $this->liftUser;
    }

    public function setLiftUser(?User $liftUser): self
    {
        $this->liftUser = $liftUser;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("name")
 * @Table(
 *     name="`user`",
 *     uniqueConstraints={
 *         @UniqueConstraint(name="email_unique",columns={"email"}),
 *         @UniqueConstraint(name="user_name_unique",columns={"name"}),
 *         @UniqueConstraint(name="user_twinoid_unique",columns={"twinoid_id"}),
 *         @UniqueConstraint(name="user_etwin_unique",columns={"eternal_id"})
 *     }
 * )
 */
class User implements UserInterface, EquatableInterface
{

    const ROLE_USER      =  0;
    const ROLE_ORACLE    =  2;
    const ROLE_CROW      =  3;
    const ROLE_ADMIN     =  4;
    const ROLE_SUPER     =  5;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pass;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserPendingValidation", mappedBy="user", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $pendingValidation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="user")
     */
    private $citizens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdminBan", mappedBy="user")
     */
    private $bannings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FoundRolePlayText", mappedBy="user", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $foundTexts;

    /**
     * @ORM\Column(type="integer")
     */
    private $soulPoints = 0;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picto", mappedBy="user", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $pictos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Award", mappedBy="user")
     */
    private $awards;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $externalId = '';

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $preferSmallAvatars = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postAsDefault;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $forumTitle;

    /**
     * This field matches to the filename of the picto
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $forumIcon;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $language = null;

    /**
     * @ORM\Column(type="smallint")
     */
    private $rightsElevation = 0;

    /**
     * @ORM\OneToMany(targetEntity=CitizenRankingProxy::class, mappedBy="user", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $pastLifes;

    /**
     * @ORM\Column(type="integer")
     */
    private $heroDaysSpent = 0;

    /**
     * @ORM\OneToOne(targetEntity=TwinoidImportPreview::class, mappedBy="user", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $twinoidImportPreview;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $twinoidID;

    /**
     * @ORM\OneToMany(targetEntity=TwinoidImport::class, mappedBy="user", orphanRemoval=true, cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $twinoidImports;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $importedSoulPoints;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $importedHeroDaysSpent;

    /**
     * @ORM\ManyToOne(targetEntity=Changelog::class)
     */
    private $latestChangelog;

    /**
     * @ORM\OneToMany(targetEntity=ConnectionIdentifier::class, mappedBy="user", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $connectionIdentifiers;

    /**
     * @ORM\OneToOne(targetEntity=ShadowBan::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $shadowBan;

    /**
     * @ORM\ManyToMany(targetEntity=ConnectionWhitelist::class, mappedBy="users", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    private $connectionWhitelists;

    /**
     * @ORM\Column(type="string", length=190, nullable=true)
     */
    private $eternalID;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $displayName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastActionTimestamp;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleteAfter;

    /**
     * @ORM\Column(type="integer")
     */
    private $checkInt = 0;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disableFx = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $expert = false;

    /**
     * @ORM\OneToMany(targetEntity=ForumThreadSubscription::class, mappedBy="user", orphanRemoval=true, fetch="EXTRA_LAZY")
     */
    private $forumThreadSubscriptions;

    /**
     * @ORM\OneToOne(targetEntity=Award::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $activeTitle;

    /**
     * @ORM\OneToOne(targetEntity=Award::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $activeIcon;

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->foundTexts = new ArrayCollection();
        $this->pictos = new ArrayCollection();
        $this->bannings = new ArrayCollection();
        $this->pastLifes = new ArrayCollection();
        $this->twinoidImports = new ArrayCollection();
        $this->connectionIdentifiers = new ArrayCollection();
        $this->connectionWhitelists = new ArrayCollection();
        $this->forumThreadSubscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->name;
    }

    public function getName(): ?string
    {
        return $this->displayName ?? $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getForumIcon(): ?string {
        return $this->forumIcon;
    }

    public function setForumIcon(string $value): self {
        $this->forumIcon = $value;

        return $this;
    }

    public function getForumTitle(): ?string {
        return $this->forumTitle;
    }

    public function setForumTitle(string $value): self {
        $this->forumTitle = $value;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSalt( ): string {
        return 'user_salt_myhordes_ffee45';
    }

    /**
     * @return Collection|AdminBan[]
     * @deprecated
     */
    public function getBannings(): Collection
    {
        return $this->bannings;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getPendingValidation(): ?UserPendingValidation
    {
        return $this->pendingValidation;
    }

    public function setPendingValidation(?UserPendingValidation $pendingValidation): self
    {
        $this->pendingValidation = $pendingValidation;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $pendingValidation ? null : $this;
        if ($pendingValidation && $pendingValidation->getUser() !== $newUser) {
            $pendingValidation->setUser($newUser);
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        $roles = [];
        if ($this->pass === null && $this->getEternalID() === null) return $roles;

        if     ($this->rightsElevation >= self::ROLE_SUPER)  $roles[] = 'ROLE_SUPER';
        elseif ($this->rightsElevation >= self::ROLE_ADMIN)  $roles[] = 'ROLE_ADMIN';
        elseif ($this->rightsElevation >= self::ROLE_CROW)   $roles[] = 'ROLE_CROW';
        elseif ($this->rightsElevation >= self::ROLE_ORACLE) $roles[] = 'ROLE_ORACLE';

        if (strstr($this->email, "@localhost") === "@localhost") $roles[] = 'ROLE_DUMMY';
        if ($this->email === 'crow') $roles[] = 'ROLE_CROW';

        if ($this->validated) $roles[] = 'ROLE_USER';
        else $roles[] = 'ROLE_REGISTERED';

        if ($this->getEternalID()) $roles[] = 'ROLE_ETERNAL';

        return array_unique($roles);
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->pass;
    }

    public function setPassword(?string $pass): self {
        $this->pass = $pass;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {}

    /**
     * @inheritDoc
     */
    public function isEqualTo(UserInterface $user) {
        if (!$this->getPassword() === null && $this->eternalID === null) return false;

templates/ajax/admin/users/citizen.html.twig
{% extends "ajax/ajax.html.twig" %}

{% from "ajax/admin/widget/displays.twig" import widget_citizen %}

{% from "ajax/admin/widget/controls.twig" import widget_status_control as status_control, widget_status_control_js as status_control_js %}
{% from "ajax/admin/widget/controls.twig" import widget_role_control as role_control, widget_role_control_js as role_control_js %}
{% from "ajax/admin/widget/controls.twig" import widget_point_control as point_control, widget_point_control_js as point_control_js %}
{% from "ajax/admin/widget/controls.twig" import widget_profession_control as profession_control, widget_profession_control_js as profession_control_js %}
{% from "ajax/admin/widget/controls.twig" import widget_home_control as home_control, widget_home_control_js as home_control_js %}
{% from "ajax/admin/widget/controls.twig" import widget_teleport_control as teleport_control, widget_teleport_control_js as teleport_control_js %}

{% block title %}{% trans from 'admin' %}Bürger{% endtrans %}{%  endblock %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-12">
            {% embed "ajax/admin/users/tabs.html.twig" %}{% endembed %}

            <div class="row">
                <div class="padded cell rw-4">
                    <h5>{{ 'Entkoppelte Leben'|trans({}, 'admin') }}</h5>
                    {% for other_life in user.citizens %}
                        {# @var other_life \App\Entity\Citizen #}
                        {% if not other_life.active %}
                            <div class="row-flex">
                                <div class="padded cell grow-0 shrink-0">
                                    {% if other_life.alive %}
                                        <img alt="{{ other_life.profession.label|trans({},'game') }}" src="{{ asset('build/images/professions/' ~ other_life.profession.icon ~ '.gif') }}" />
                                    {% else %}
                                        <img alt="{{ 'Tot!'|trans({},'game') }}" src="{{ asset('build/images/professions/death.gif') }}" />
                                    {% endif %}
                                </div>
                                <div class="padded cell grow-1 shrink-1">
                                    {{ other_life.town.name }}
                                </div>
                                <div class="padded cell grow-0 shrink-0">
                                    <button {% if not is_granted("ROLE_ADMIN") or not other_life.alive %}disabled{% endif %} x-engage="{{ path('admin_users_citizen_engage', {id: user.id, cid: other_life.id}) }}"><i class="fa fa-recycle"></i></button>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="cell rw-8">
                    <div class="row">
                        <div class="cell padded rw-12">
                            <h5>{{ 'Derzeitiges Leben'|trans({}, 'admin') }}</h5>
                            {% if alive %}
                                <div class="tooltip">{{ widget_citizen(user_citizen) }}</div>
                            {% endif %}
                        </div>
                        <div class="cell padded rw-12" {% if user_citizen is not null %}id="citizen_base_selector" x-id="{{ user_citizen.id }}"{% endif %}>
                            <label><input disabled style="width: 25em;" value="{% if active %}{{ town.name }}{% if not alive %}{{ " -- " }}{{ 'TOD NICHT BESTÄTIGT'|trans({}, 'admin') }}{% endif %}{% else %}{{ "--" }}{% endif %}" /></label>
                        </div>
                        {% if active %}
                            {% if alive %}
                                <div class="cell padded rw-3">
                                    <button id="x-headshot">{{ 'Kopfschuss'|trans({}, 'admin') }}</button>
                                </div>
                                <div class="cell padded rw-3">
                                    <button {% if not is_granted("ROLE_ADMIN") %}disabled{% endif %} x-engage="{{ path('admin_users_citizen_engage', {id: user.id, cid: 0}) }}">{{ 'Entkoppeln'|trans({}, 'admin') }}</button>
                                </div>
                                <div class="cell padded rw-3">
                                    <button id="x-pm">{{ 'PM vom Raben'|trans({}, 'admin') }}</button>
                                </div>
                                <div class="cell padded rw-3">
                                    <button x-ajax-href="{{ path("admin_town_explorer", {id: town.id}) }}">{{ 'Stadt ansehen'|trans({}, 'admin') }}</button>
                                </div>

                                {% if is_granted("ROLE_ADMIN") %}
                                    <div class="cell padded rw-6">{{ point_control() }}</div>
                                    <div class="cell padded rw-6">{{ profession_control(citizenProfessions) }}</div>
                                    <div class="cell padded rw-12">{{ teleport_control() }}</div>
                                    <div class="cell padded rw-6">{{ status_control(citizenStati) }}</div>
                                    <div class="cell padded rw-6">{{ role_control(citizenRoles) }}</div>
                                    <div class="cell padded rw-12">{{ home_control(user_citizen,home_upgrades) }}</div>
                                {% endif %}
                            {% else %}
                                {% if is_granted("ROLE_ADMIN") %}
                                    <div class="cell padded rw-4">
                                        <button id="x-confirm-death">{{ 'Tod bestätigen'|trans({}, 'admin') }}</button>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="cell padded rw-12">
                            <input type="hidden" id="pmidrecipient" value="{{ citizen_id }}">
                            <div id="forum-content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    {% if is_granted("ROLE_ADMIN") and alive %}
        {{ home_control_js('#citizen_base_selector', path('admin_town_manage_home', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
        {{ status_control_js('#citizen_base_selector', path('admin_town_manage_status', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
        {{ role_control_js('#citizen_base_selector', path('admin_town_manage_role', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
        {{ point_control_js('#citizen_base_selector', path('admin_town_alter_pp', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
        {{ profession_control_js('#citizen_base_selector', path('admin_modify_profession', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
        {{ teleport_control_js('#citizen_base_selector', path('admin_teleport_citizen', {id: user_citizen.town.id}), path('admin_users_citizen_view', {id: user.id})) }}
    {% endif %}
    <script>
        {% if is_granted("ROLE_ADMIN") %}
            $.html.addEventListenerAll('[x-engage]', 'click', (e,elem) => {
                $.ajax.easySend( elem.getAttribute('x-engage'), [],
                    function () {
                        $.ajax.load(null, '{{ path('admin_users_citizen_view', { 'id': user.Id }) }}', true);
                    } )
            });
        {% endif %}

        {% if active %}
            {% if alive %}
                document.getElementById('x-headshot').addEventListener('click', function(e) {
                    e.preventDefault();
                    if (confirm('{{ 'Das Leben dieses Bürgers sofort beenden?'|trans({},'admin') }}'))
                        $.ajax.easySend( '{{ path('admin_users_citizen_headshot', { 'id': user.Id }) }}', [],
                            function () {
                                $.ajax.load(null, '{{ path('admin_users_citizen_view', { 'id': user.Id }) }}', true);
                            } )
                });

                document.getElementById('x-pm').addEventListener('click', function(e) {
                    document.getElementById("forum-content").innerHTML = "";
                    $.ajax.no_history().load( document.getElementById('forum-content'), '{{ path('admin_pm_editor_controller', {'type': 'pm'}) }}', false )
                });
            {% elseif is_granted("ROLE_ADMIN") %}
                document.getElementById('x-confirm-death').addEventListener('click', function(e) {
                    e.preventDefault();
                    if (confirm('{{ 'Tod dieses Bürgers zwangsweise bestätigen?'|trans({},'admin') }}'))
                        $.ajax.easySend( '{{ path('admin_users_citizen_confirm_death', { 'id': user.Id }) }}', [],
                            function () {
                                $.ajax.load(null, '{{ path('admin_users_citizen_view', { 'id': user.Id }) }}', true);
                            } )
                });
            {% endif %}
        {% endif %}


    </script>
{% endblock %}

templates/ajax/admin/users/footer.html.twig
<div class="row">
    <div class="cell padded rw-12 rw-sm-12">
        <div id="users-list-admin">
            <h5>{{'Suche:'|trans({}, "admin")}}</h5>
            {% include 'ajax/admin/snippets/user_search.html.twig' %}
        </div>
    </div>
</div>
{% block js %}
    <script>
        let typingTimer, doneTypingInterval = 500;
        let searchBox = document.getElementById('user-search');

        const userSearchHandler = function() {
            $.ajax.background().load(
                document.getElementById('users-list'),
                '{{ path('admin_users_fuzzyfind') }}',
                false,
                {'name': searchBox.value}
            );
        };

        const userSearchHandlerUp = function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(userSearchHandler, doneTypingInterval);
        };

        const userSearchHandlerDown = function () {
            clearTimeout(typingTimer);
        };

        searchBox.addEventListener('keyup', userSearchHandlerUp);
        searchBox.addEventListener('keydown', userSearchHandlerDown);
    </script>
{% endblock %}

templates/ajax/admin/users/index.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    {% embed "ajax/admin/users/footer.html.twig" %}{% endembed %}
    <div class="row">
        <div class="cell rw-12">
            <h5>{{'Multi-Account Report'|trans({}, "admin")}}</h5>
            <div class="row-table">
                <div class="row header">
                    <div class="cell padded rw-1">&nbsp;</div>
                    <div class="cell padded rw-3">{{ 'Benutzername'|trans({},'admin') }}</div>
                    <div class="cell padded rw-2">{{ 'Verdacht'|trans({},'admin') }}</div>
                    <div class="cell padded rw-6">{{ 'Andere Accounts'|trans({},'admin') }}</div>
                </div>
                {% for table in ma_report %}
                    {% if not table.principal|restricted(constant('App\\Entity\\AccountRestriction::RestrictionGameplay')) %}
                    {# @var table \App\Structures\CheatTable #}
                        <div class="row">
                            <div class="cell rw-4 padded">
                                <b>{{ table.principal.name }}</b>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <br /><span>{{ table.principal.email }}</span>
                                {% endif %}
                            </div>
                            <div class="cell rw-2 padded">
                                {{ table.likeliness }}
                            </div>
                            <div class="cell {% if is_granted('ROLE_ADMIN') %}rw-5{% else %}rw-6{% endif %}">
                                {% set group = [] %}
                                {% for multi in table.users %}
                                    {% set group = group|merge([multi.id]) %}
                                    <span class="small pointer" x-whitelist-alt="{{ url('admin_users_account_view', {id: multi.id}) }}" x-whitelist="{{ group|join('|') }}" x-api-endpoint="{{ url('admin_users_account_manage', {action: 'whitelist', id: table.principal.id}) }}" {% if multi|restricted(constant('App\\Entity\\AccountRestriction::RestrictionGameplay')) %}style="color:red; font-weight: bold"{% endif%} >
                                        {{ multi.name }}
                                        {% if is_granted('ROLE_ADMIN') %}
                                            <div class="tooltip">
                                                <i>({{ multi.id }})</i> <b>{{ multi.email }}</b>
                                                <hr/>
                                                <i>{{ 'Klick, um Profil in neuem Tab zu öffnen'|trans({},'admin') }}</i>
                                                <hr/>
                                                <i>{{ 'STRG+Klick, um zur Whitelist hinzuzufügen'|trans({},'admin') }}</i>
                                            </div>
                                        {% endif %}
                                    </span>&nbsp;
                                {% endfor %}
                            </div>
                            {% if is_granted('ROLE_ADMIN') %}
                                <div class="cell rw-1 padded">
                                    <button x-shadow x-api-endpoint="{{ url('admin_users_account_manage', {action: 'shadow',    id: table.principal.id}) }}">{{ 'Bann'|trans({},'admin') }}</button>
                                    <button x-whitelist="{{ group|join('|') }}" x-api-endpoint="{{ url('admin_users_account_manage', {action: 'whitelist', id: table.principal.id}) }}">{{ 'Whitelist'|trans({},'admin') }}</button>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% if is_granted("ROLE_ADMIN") %}
            $.html.addEventListenerAll('[x-shadow][x-api-endpoint]', 'click', function(e,elem) {
                if (confirm("{{ 'Bestätigen?'|trans({},'global')|e('js') }}\nBAN"))
                    $.ajax.easySend( elem.getAttribute('x-api-endpoint'), {param: 'Multi Account'},
                        function () {
                            $.ajax.load(null, '{{ path('admin_users') }}', true);
                        } );
            });
        $.html.addEventListenerAll('[x-whitelist][x-api-endpoint]', 'click', function(e,elem) {
            if ((!elem.hasAttribute('x-whitelist-alt') || e.ctrlKey) && confirm("{{ 'Bestätigen?'|trans({},'global')|e('js') }}\nWHITELIST"))
                $.ajax.easySend( elem.getAttribute('x-api-endpoint'), {param: elem.getAttribute('x-whitelist').split('|')},
                    function () {
                        $.ajax.load(null, '{{ path('admin_users') }}', true);
                    } );
        });
        $.html.addEventListenerAll('[x-whitelist][x-whitelist-alt][x-api-endpoint]', 'click', function(e,elem) {
            if (!e.ctrlKey) window.open(elem.getAttribute('x-whitelist-alt'),'_blank');
        });
        {% endif %}
    </script>
{% endblock %}